
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$registry = $objectManager->get('\Magento\Framework\Registry');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$currentProduct = $registry->registry('current_product');
$id_pro=$currentProduct->getId();
$sku_pro=$currentProduct->getSku();
$image_enable=$currentProduct->getData('image_360_enable');

if($image_enable) { ?>
<script>

require(['jquery'], function() {
    window.addEventListener('load', function() { setTimeout(function(){
        jQuery(document).ready(function() {
var $sku = jQuery(".product.attribute.sku .value").text();
var $fotorama = jQuery('div.gallery-placeholder > div.fotorama');
var fotorama = [];
fotorama = $fotorama.data('fotorama');
$fotorama.on('fotorama:load', function fotorama_onLoad(e, fotorama, extra) {
    if (extra.frame.type === 'iframe') {
        extra.frame.$stageFrame.html('<iframe type="text/html" width="100%" height="100%" src="' + extra.frame.src + '" frameborder="0" scrolling="no" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>');
    }
});
fotorama.unshift({ img: '<?php echo $this->getViewFileUrl('Askantech_Threesixty::images/360.png'); ?>', thumb: '<?php echo $this->getViewFileUrl('Askantech_Threesixty::images/360.png'); ?>', 'src': "<?php echo $baseUrl; ?>Threesixty?sv=<?php echo $sku_pro;?>&iv=<?php echo $id_pro;?>", type: 'iframe' });
        });
},3000); });
});

</script>
<?php } ?>
